name: my_alquran
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
#  alice: ^0.1.12
  bloc: ^6.1.3
  dio: ^3.0.10
  equatable: ^2.0.0
  flutter_bloc: ^6.1.3
#  flutter_local_notifications: ^4.0.1+2
  google_fonts: 1.1.2
  relative_scale: ^2.0.0
  audioplayers: ^0.18.1
  modal_bottom_sheet: ^2.0.0
  share: ^2.0.1
  flutter_svg: ^0.19.3
  intl: ^0.17.0
  geolocator: ^7.0.1
  geocoding: ^2.0.0
  date_format: ^2.0.2
  hijri: ^2.0.3
  rxdart: ^0.26.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:


  uses-material-design: true

  assets:
    - image/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#    fonts:
#       - family: Traditional Arabic
#         fonts:
#           - asset: fonts/tradbdo.ttf
#           - asset: fonts/trado.ttf

  fonts:
    - family: Traditional Arabic
      fonts:
        - asset: fonts/tradbdo.ttf
        - asset: fonts/trado.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
